#:schema node_modules/wrangler/config-schema.json
name = "manamurah-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
MANAMURAH_API_BASE = "https://api.manamurah.com"
RATE_LIMIT_ENABLED = "true"
CACHE_TTL = "300"
MAX_QUERIES_PER_MINUTE = "10"
MAX_QUERIES_PER_HOUR = "100"

# Environment-specific configurations
[env.production]
name = "manamurah-mcp-server"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "manamurah-mcp-server-staging"
vars = { ENVIRONMENT = "staging" }

[env.development]
name = "manamurah-mcp-server-dev"
vars = { ENVIRONMENT = "development" }

# Custom domains
[[routes]]
pattern = "mcp.manamurah.com"
custom_domain = true

# KV namespace for rate limiting (optional)
# [[kv_namespaces]]
# binding = "MCP_CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"